spring.application.name=laboratorio05a

# Configuración de base de datos MySQL (por defecto para ejecución local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_swad_lab05?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
